# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
#
#   smidump -f python EXTREME-SOFTWARE-MONITOR-MIB

FILENAME = "mibs/Extreme Networks/EXTREME-SOFTWARE-MONITOR-MIB.mib"

MIB = {
    "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",

    "EXTREME-SOFTWARE-MONITOR-MIB" : {
        "nodetype" : "module",
        "language" : "SMIv2",
        "organization" :    
            """Extreme Networks, Inc.""",
        "contact" : 
            """www.extremenetworks.com""",
        "description" :
            """Extreme Software Monitor objects: objects common to all platforms""",
        "revisions" : (
            {
                "date" : "2013-09-20 10:06",
                "description" :
                    """[Revision added by libsmi due to a LAST-UPDATED clause.]""",
            },
        ),
        "identity node" : "extremeSwMonitor",
    },

    "imports" : (
        {"module" : "SNMPv2-SMI", "name" : "MODULE-IDENTITY"},
        {"module" : "SNMPv2-SMI", "name" : "NOTIFICATION-TYPE"},
        {"module" : "SNMPv2-SMI", "name" : "OBJECT-TYPE"},
        {"module" : "SNMPv2-SMI", "name" : "Unsigned32"},
        {"module" : "SNMPv2-TC", "name" : "DisplayString"},
        {"module" : "EXTREME-BASE-MIB", "name" : "extremeAgent"},
        {"module" : "", "name" : "extremeImageDescription"},
        {"module" : "EXTREME-BASE-MIB", "name" : "PortList"},
    ),

    "nodes" : {
        "extremeSwMonitor" : {
            "nodetype" : "node",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32",
            "status" : "current",
        }, # node
        "extremeSwMonitorCpu" : {
            "nodetype" : "node",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1",
        }, # node
        "extremeCpuMonitorInterval" : {
            "nodetype" : "scalar",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "5",
                        "max" : "60"
                    },
                    ],
                    "range" : {
                        "min" : "5",
                        "max" : "60"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Cpu monitoring interval in seconds. Can not be smaller
then 5 seconds.""",
        }, # scalar
        "extremeCpuMonitorTotalUtilization" : {
            "nodetype" : "scalar",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Total CPU utlization (percentage) as of last sampling.""",
        }, # scalar
        "extremeCpuMonitorTable" : {
            "nodetype" : "table",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.3",
            "status" : "current",
            "description" :
                """Table of CPU processes that are active.""",
        }, # table
        "extremeCpuMonitorEntry" : {
            "nodetype" : "row",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.3.1",
            "status" : "current",
            "implied" : "true",
            "linkage" : [
                "extremeCpuMonitorSlotId",
                "extremeCpuMonitorProcessName",
            ],
            "description" :
                """An entry in table of describes a single process.""",
        }, # row
        "extremeCpuMonitorSlotId" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.3.1.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Unsigned32"},
            },
            "access" : "readonly",
            "description" :
                """Slot Id of the process monitored.""",
        }, # column
        "extremeCpuMonitorProcessName" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.3.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "31"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "31"
                    },
                },
            },
            "access" : "noaccess",
            "description" :
                """Name associated with the reported process id.""",
        }, # column
        "extremeCpuMonitorProcessId" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.3.1.3",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Unsigned32"},
            },
            "access" : "readonly",
            "description" :
                """Process identifier assigned by the operating system when
this process is created.""",
        }, # column
        "extremeCpuMonitorProcessState" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.3.1.4",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The current state of the process as reported by Extremeware XOS.""",
        }, # column
        "extremeCpuMonitorUtilization5secs" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.3.1.5",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The CPU utilization by this process. This
is the utilization of the process in the last 5 seconds.""",
        }, # column
        "extremeCpuMonitorUtilization10secs" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.3.1.6",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The CPU utilization by this process. This
is the utilization of the process in the last 10 seconds.""",
        }, # column
        "extremeCpuMonitorUtilization30secs" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.3.1.7",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The CPU utilization by this process. This
is the utilization of the process in the last 30 seconds.""",
        }, # column
        "extremeCpuMonitorUtilization1min" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.3.1.8",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The CPU utilization by this process. This
is the utilization of the process in the last 1 minute.""",
        }, # column
        "extremeCpuMonitorUtilization5mins" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.3.1.9",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The CPU utilization by this process. This
is the utilization of the process in the last 5 minutes.""",
        }, # column
        "extremeCpuMonitorUtilization30mins" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.3.1.10",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The CPU utilization by this process. This
is the utilization of the process in the last 30 minutes.""",
        }, # column
        "extremeCpuMonitorUtilization1hour" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.3.1.11",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The CPU utilization by this process. This
is the utilization of the process in the last 1 hour.""",
        }, # column
        "extremeCpuMonitorMaxUtilization" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.3.1.12",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The maximum CPU utilization by this process since
the time the start started executing. """,
        }, # column
        "extremeCpuMonitorUserTime" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.3.1.13",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The amount of time process spend in application space from 
the time the process started executing. """,
        }, # column
        "extremeCpuMonitorSystemTime" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.3.1.14",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The amount of time process spend in kernel space from
the time the process started executing. """,
        }, # column
        "extremeCpuMonitorSystemTable" : {
            "nodetype" : "table",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.4",
            "status" : "current",
            "description" :
                """Table of CPU utilization for system processes.""",
        }, # table
        "extremeCpuMonitorSystemEntry" : {
            "nodetype" : "row",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.4.1",
            "status" : "current",
            "linkage" : [
                "extremeCpuMonitorSystemSlotId",
            ],
            "description" :
                """An entry in table of describes a single slot CPU 
utilization.""",
        }, # row
        "extremeCpuMonitorSystemSlotId" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.4.1.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Unsigned32"},
            },
            "access" : "readonly",
            "description" :
                """Slot Id of the system monitored.""",
        }, # column
        "extremeCpuMonitorSystemUtilization5secs" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.4.1.5",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The CPU utilization by set of system resources. This
is the utilization of the process in the last 5 seconds.""",
        }, # column
        "extremeCpuMonitorSystemUtilization10secs" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.4.1.6",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The CPU utilization by set of system resources This
is the utilization of the system resources in the last 10 seconds.""",
        }, # column
        "extremeCpuMonitorSystemUtilization30secs" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.4.1.7",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The CPU utilization by system resources process. This
is the utilization of the system resources in the last 30 seconds.""",
        }, # column
        "extremeCpuMonitorSystemUtilization1min" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.4.1.8",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The CPU utilization by system resources. This
is the utilization of the system resources in the last 1 minute.""",
        }, # column
        "extremeCpuMonitorSystemUtilization5mins" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.4.1.9",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The CPU utilization by system resources. This
is the utilization of the system resourcesin the last 5 minutes.""",
        }, # column
        "extremeCpuMonitorSystemUtilization30mins" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.4.1.10",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The CPU utilization by system resources. This
is the utilization of the system resources in the last 30 minutes.""",
        }, # column
        "extremeCpuMonitorSystemUtilization1hour" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.4.1.11",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The CPU utilization by this process. This
is the utilization of the process in the last 1 hour.""",
        }, # column
        "extremeCpuMonitorSystemMaxUtilization" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.4.1.12",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """The maximum CPU utilization by this process since
the time the start started executing. """,
        }, # column
        "extremeCpuMonitorThreshold" : {
            "nodetype" : "scalar",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Threshold for CPU Aggregation utilization trap""",
        }, # scalar
        "extremeCpuMonitorCurrentUtilization" : {
            "nodetype" : "scalar",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.1.6",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "notifyonly",
            "description" :
                """Percentage of the amount of time recorded in seconds that the process spends occupying CPU resources.  This value is reported in extremeSwMonitorCpuUtilization and extremeSwMonitorCpuUtilizationNormal trap.""",
        }, # scalar
        "extremeSwMonitorMemory" : {
            "nodetype" : "node",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2",
        }, # node
        "extremeMemoryMonitorSystemTable" : {
            "nodetype" : "table",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.2",
            "status" : "current",
            "description" :
                """Table of Memory consumption for processes that are active.""",
        }, # table
        "extremeMemoryMonitorSystemEntry" : {
            "nodetype" : "row",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.2.1",
            "status" : "current",
            "linkage" : [
                "extremeMemoryMonitorSystemSlotId",
            ],
            "description" :
                """An entry in table of describes a single process.""",
        }, # row
        "extremeMemoryMonitorSystemSlotId" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.2.1.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Unsigned32"},
            },
            "access" : "readonly",
            "description" :
                """Slot Id of the MSM monitored.""",
        }, # column
        "extremeMemoryMonitorSystemTotal" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.2.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "8"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "8"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Total amount of DRAM in Kbytes in the system.""",
        }, # column
        "extremeMemoryMonitorSystemFree" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.2.1.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "8"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "8"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Total amount of free memory in Kbytes in the system.""",
        }, # column
        "extremeMemoryMonitorSystemUsage" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.2.1.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "8"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "8"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Total amount of memory used by system services in Kbytes in the system.""",
        }, # column
        "extremeMemoryMonitorUserUsage" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.2.1.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "8"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "8"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Total amount of memory used by applications in Kbytes in the system.""",
        }, # column
        "extremeMemoryMonitorTable" : {
            "nodetype" : "table",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.3",
            "status" : "current",
            "description" :
                """Table of Memory consumption for processes that are active.""",
        }, # table
        "extremeMemoryMonitorEntry" : {
            "nodetype" : "row",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.3.1",
            "status" : "current",
            "implied" : "true",
            "linkage" : [
                "extremeMemoryMonitorSlotId",
                "extremeMemoryMonitorProcessName",
            ],
            "description" :
                """An entry in table of describes a single process.""",
        }, # row
        "extremeMemoryMonitorSlotId" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.3.1.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Unsigned32"},
            },
            "access" : "readonly",
            "description" :
                """Slot Id of the process monitored.""",
        }, # column
        "extremeMemoryMonitorProcessName" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.3.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "31"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "31"
                    },
                },
            },
            "access" : "noaccess",
            "description" :
                """Name associated with the reported process.""",
        }, # column
        "extremeMemoryMonitorUsage" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.3.1.3",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Unsigned32"},
            },
            "access" : "readonly",
            "description" :
                """Current memory consumption in Kbytes for the process.""",
        }, # column
        "extremeMemoryMonitorLimit" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.3.1.4",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Unsigned32"},
            },
            "access" : "readonly",
            "description" :
                """Maximum memory consumption in Kbytes for the process.""",
        }, # column
        "extremeMemoryMonitorZone" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.3.1.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "8"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "8"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Current process memory consumption zone. Zones are Green (up to 70% cosumption), Yellow (70-80%), Orange (80-90%), Red (90-95%) either total cpu consumption or memory consumption limit configured per process.""",
        }, # column
        "extremeMemoryMonitorGreenZoneCount" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.3.1.6",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Unsigned32"},
            },
            "access" : "readonly",
            "description" :
                """Number of times process moved to green zone.""",
        }, # column
        "extremeMemoryMonitorYellowZoneCount" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.3.1.7",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Unsigned32"},
            },
            "access" : "readonly",
            "description" :
                """Number of times process moved from green to yellow zone.""",
        }, # column
        "extremeMemoryMonitorOrangeZoneCount" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.3.1.8",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Unsigned32"},
            },
            "access" : "readonly",
            "description" :
                """Number of times process moved from yellow zone to orange.""",
        }, # column
        "extremeMemoryMonitorRedZoneCount" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.3.1.9",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Unsigned32"},
            },
            "access" : "readonly",
            "description" :
                """Number of times process moved from orange zone to red.""",
        }, # column
        "extremeMemoryMonitorGreenZoneThreshold" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.3.1.10",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Unsigned32"},
            },
            "access" : "readonly",
            "description" :
                """Percentage of memory consumption that defines green zone.""",
        }, # column
        "extremeMemoryMonitorYellowZoneThreshold" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.3.1.11",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Unsigned32"},
            },
            "access" : "readonly",
            "description" :
                """Percentage of memory consumption that defines yellow zone.""",
        }, # column
        "extremeMemoryMonitorOrangeZoneThreshold" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.3.1.12",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Unsigned32"},
            },
            "access" : "readonly",
            "description" :
                """Percentage of memory consumption that defines orange zone.""",
        }, # column
        "extremeMemoryMonitorRedZoneThreshold" : {
            "nodetype" : "column",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.2.3.1.13",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Unsigned32"},
            },
            "access" : "readonly",
            "description" :
                """Percentage of memory consumption that defines red zone.""",
        }, # column
        "extremeSwMonitorNotifications" : {
            "nodetype" : "node",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.3",
        }, # node
        "extremeSwMonitorNotificationsPrefix" : {
            "nodetype" : "node",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.3.0",
        }, # node
        "extremeServiceLicense" : {
            "nodetype" : "node",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.4",
        }, # node
        "extremeServiceLicenseExpiryDate" : {
            "nodetype" : "scalar",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.4.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "notifyonly",
            "description" :
                """This report the expiration date of the license.""",
        }, # scalar
        "extremeServiceLicenseType" : {
            "nodetype" : "scalar",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.4.2",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "notifyonly",
            "description" :
                """This report the service license type.""",
        }, # scalar
        "imageDescription" : {
            "nodetype" : "scalar",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.4.3",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "notifyonly",
            "description" :
                """This report the image version on which license was enabled.""",
        }, # scalar
        "noOfDaysLeft" : {
            "nodetype" : "scalar",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.4.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "90"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "90"
                    },
                },
            },
            "access" : "notifyonly",
            "description" :
                """This report the number of days left to service license expire.""",
        }, # scalar
        "extremeTrialLicense" : {
            "nodetype" : "node",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.5",
        }, # node
        "trialPeriod" : {
            "nodetype" : "scalar",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.5.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "90"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "90"
                    },
                },
            },
            "access" : "notifyonly",
            "description" :
                """This report the number of days left to service license expire.""",
        }, # scalar
    }, # nodes

    "notifications" : {
        "extremeSwMonitorCpuUtilization" : {
            "nodetype" : "notification",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.3.0.1",
            "status" : "current",
            "objects" : {
                "extremeCpuMonitorSlotId" : {
                    "nodetype" : "object",
                    "module" : "EXTREME-SOFTWARE-MONITOR-MIB"
                },
                "extremeCpuMonitorProcessName" : {
                    "nodetype" : "object",
                    "module" : "EXTREME-SOFTWARE-MONITOR-MIB"
                },
                "extremeCpuMonitorCurrentUtilization" : {
                    "nodetype" : "object",
                    "module" : "EXTREME-SOFTWARE-MONITOR-MIB"
                },
                "extremeCpuMonitorThreshold" : {
                    "nodetype" : "object",
                    "module" : "EXTREME-SOFTWARE-MONITOR-MIB"
                },
            },
            "description" :
                """Notification of process exceeding CPU utilization threshold. Notification is send every extremeCpuMonitorInterval value in seconds until utilization falls below threshold.""",
        }, # notification
        "extremeServiceLicenseExpiration" : {
            "nodetype" : "notification",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.3.0.2",
            "status" : "current",
            "objects" : {
                "extremeServiceLicenseExpiryDate" : {
                    "nodetype" : "object",
                    "module" : "EXTREME-SOFTWARE-MONITOR-MIB"
                },
                "extremeServiceLicenseType" : {
                    "nodetype" : "object",
                    "module" : "EXTREME-SOFTWARE-MONITOR-MIB"
                },
                "imageDescription" : {
                    "nodetype" : "object",
                    "module" : "EXTREME-SOFTWARE-MONITOR-MIB"
                },
                "noOfDaysLeft" : {
                    "nodetype" : "object",
                    "module" : "EXTREME-SOFTWARE-MONITOR-MIB"
                },
            },
            "description" :
                """The service expiry notification is generated about 90 days service contract expiration, then 60,30,7 days and daily after that.""",
        }, # notification
        "extremeTrialLicenseExpiration" : {
            "nodetype" : "notification",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.3.0.3",
            "status" : "current",
            "objects" : {
                "trialPeriod" : {
                    "nodetype" : "object",
                    "module" : "EXTREME-SOFTWARE-MONITOR-MIB"
                },
                "imageDescription" : {
                    "nodetype" : "object",
                    "module" : "EXTREME-SOFTWARE-MONITOR-MIB"
                },
                "noOfDaysLeft" : {
                    "nodetype" : "object",
                    "module" : "EXTREME-SOFTWARE-MONITOR-MIB"
                },
            },
            "description" :
                """Trial license expiry notification is generated every day.""",
        }, # notification
        "extremeSwMonitorCpuUtilizationNormal" : {
            "nodetype" : "notification",
            "moduleName" : "EXTREME-SOFTWARE-MONITOR-MIB",
            "oid" : "1.3.6.1.4.1.1916.1.32.3.0.4",
            "status" : "current",
            "objects" : {
                "extremeCpuMonitorSlotId" : {
                    "nodetype" : "object",
                    "module" : "EXTREME-SOFTWARE-MONITOR-MIB"
                },
                "extremeCpuMonitorProcessName" : {
                    "nodetype" : "object",
                    "module" : "EXTREME-SOFTWARE-MONITOR-MIB"
                },
                "extremeCpuMonitorCurrentUtilization" : {
                    "nodetype" : "object",
                    "module" : "EXTREME-SOFTWARE-MONITOR-MIB"
                },
                "extremeCpuMonitorThreshold" : {
                    "nodetype" : "object",
                    "module" : "EXTREME-SOFTWARE-MONITOR-MIB"
                },
            },
            "description" :
                """Notification of process CPU utilization falling below threshold.  The generation of this notification corresponds with the extremeSwMonitorCpuUtilization (CPU excessed threshold) notification.  When the CPU utilization of the process that triggered the extremeSwMonitorCpuUtilization notification falls back below the configured threshold, this (return to normal) notification will be generated.""",
        }, # notification
    }, # notifications

}
