# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
#
#   smidump -f python TPLINK-SYSMONITOR-MIB

FILENAME = "mibs/TP-Link/tplink-sysMonitor.mib"

MIB = {
    "moduleName" : "TPLINK-SYSMONITOR-MIB",

    "TPLINK-SYSMONITOR-MIB" : {
        "nodetype" : "module",
        "language" : "SMIv2",
        "organization" :    
            """TPLINK""",
        "contact" : 
            """www.tplink.com.cn""",
        "description" :
            """Private MIB for System Monitor.""",
        "revisions" : (
            {
                "date" : "2012-12-11 09:30",
                "description" :
                    """[Revision added by libsmi due to a LAST-UPDATED clause.]""",
            },
        ),
        "identity node" : "tplinkSysMonitorMIB",
    },

    "imports" : (
        {"module" : "SNMPv2-SMI", "name" : "MODULE-IDENTITY"},
        {"module" : "SNMPv2-SMI", "name" : "OBJECT-TYPE"},
        {"module" : "SNMPv2-SMI", "name" : "NOTIFICATION-TYPE"},
        {"module" : "TPLINK-MIB", "name" : "tplinkMgmt"},
    ),

    "nodes" : {
        "tplinkSysMonitorMIB" : {
            "nodetype" : "node",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4",
            "status" : "current",
        }, # node
        "tplinkSysMonitorMIBObjects" : {
            "nodetype" : "node",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4.1",
        }, # node
        "tpSysMonitorCpu" : {
            "nodetype" : "node",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4.1.1",
        }, # node
        "tpSysMonitorCpuTable" : {
            "nodetype" : "table",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4.1.1.1",
            "status" : "current",
            "description" :
                """Displays the CPU utilization of all UNITs.""",
        }, # table
        "tpSysMonitorCpuEntry" : {
            "nodetype" : "row",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4.1.1.1.1",
            "status" : "current",
            "linkage" : [
                "tpSysMonitorCpuUnitNumber",
            ],
            "description" :
                """An entry contains of the information of CPU utilization.""",
        }, # row
        "tpSysMonitorCpuUnitNumber" : {
            "nodetype" : "column",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4.1.1.1.1.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readonly",
            "description" :
                """Displays the UNIT number.""",
        }, # column
        "tpSysMonitorCpu5Seconds" : {
            "nodetype" : "column",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4.1.1.1.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Displays the CPU utilization in 5 seconds.""",
        }, # column
        "tpSysMonitorCpu1Minute" : {
            "nodetype" : "column",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4.1.1.1.1.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Displays the CPU utilization in 1 minute.""",
        }, # column
        "tpSysMonitorCpu5Minutes" : {
            "nodetype" : "column",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4.1.1.1.1.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Displays the CPU utilization in 5 minutes.""",
        }, # column
        "tpSysMonitorMemory" : {
            "nodetype" : "node",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4.1.2",
        }, # node
        "tpSysMonitorMemoryTable" : {
            "nodetype" : "table",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4.1.2.1",
            "status" : "current",
            "description" :
                """Displays the memory utilization of all UNITs.""",
        }, # table
        "tpSysMonitorMemoryEntry" : {
            "nodetype" : "row",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4.1.2.1.1",
            "status" : "current",
            "linkage" : [
                "tpSysMonitorMemoryUnitNumber",
            ],
            "description" :
                """An entry contains of the information of memory utilization.""",
        }, # row
        "tpSysMonitorMemoryUnitNumber" : {
            "nodetype" : "column",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4.1.2.1.1.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readonly",
            "description" :
                """Displays the UNIT number.""",
        }, # column
        "tpSysMonitorMemoryUtilization" : {
            "nodetype" : "column",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4.1.2.1.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Displays the memory utilization.""",
        }, # column
        "tplinkSysMonitorNotifications" : {
            "nodetype" : "node",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4.2",
        }, # node
    }, # nodes

    "notifications" : {
        "tpSysMonitorCpuOverLoading" : {
            "nodetype" : "notification",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4.2.1",
            "status" : "current",
            "objects" : {
            },
            "description" :
                """CPU utilization reached the threshold.""",
        }, # notification
        "tpSysMonitorMemoryOverLoading" : {
            "nodetype" : "notification",
            "moduleName" : "TPLINK-SYSMONITOR-MIB",
            "oid" : "1.3.6.1.4.1.11863.6.4.2.2",
            "status" : "current",
            "objects" : {
            },
            "description" :
                """Memory utilization reached the threshold.""",
        }, # notification
    }, # notifications

}
